services:
  chatio-front:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: chatio-front-dev
    container_name: chatio-front-dev
    ports:
      - "3300:3300"